<a href="https://colab.research.google.com/github/A7sultan/Python-DA-ML-portfolio/blob/main/Aminah_day6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


DATA ANALYSIS:

used to analyse the datya and draw insights from it.

The 5 most imp libraries in DA
1. numpy
2. pandas
3. matplotlib
4. seaborn
5. scikit learn

NUMPY: (import numpy)

Numerical python

np.array()- function of an array    



In [ ]:
import numpy as np
my_arr=np.array([1,2,3,4,5])  #syntax for array function
array1=np.array(["gogh", "Da vince", "lucifer"])
print(my_arr)
print(my_arr.dtype)   #for array data type
print(array1.dtype)

array2=np.array([1,2,3,4,5,6,7,8])
array2[5]        #for accessing elements of an array
print(array2[0]) #indexing
print(array2[4]+array2[5])  #addition

print(array2[::2])
print(array2[:6:2])   #Slicing
a=(array2[::-1])  #for reversing  the array, the step should have a negative index of 1 i.e step=-1
print(a)

[1 2 3 4 5]
int64
<U8
1
11
[1 3 5 7]
[1 3 5]
[8 7 6 5 4 3 2 1]


2D, 3D arrays

In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1[0])
print(arr1[1])
print(arr1.shape)  #arr_name.shape gives the rows,cols of the matrix
print(arr1[0][1])  #arr_name[row][col]
arr2=np.array([1,2,3,4,5,6,7,8,9,10,11,12], ndmin=4)
print(arr2.shape)
new_arr=arr2.reshape(4,3)   #arr_name.reshape for shaping a matrix into n dimensions
print(new_arr)
arr3=arr2.reshape(2,3,2)   #reshape(r,d,c)  rxdxc=no.elements
print(arr3)
print(arr3.ndim)       #arr_name.ndim gives the number of dimensions
arr4=arr2.reshape(3,2,2)
print(arr4)
print(arr4.ndim)
print(arr1)
arr5=arr1.reshape(-1)   #changes any dimensions to 1D on reshaping with (-1)
print(arr5)

[1 2 3]
[4 5 6]
(2, 3)
2
(1, 1, 1, 12)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


Iterating the arrays

In [ ]:
arr6=np.array([[1,2,3],[4,5,6]])
for element in arr6:     # 2 for loops for 2D array
   for ele in element:
    print(ele)

arr7=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,6,7]]])
for a in arr7:
  for b in a:
    for c in b:
      print(c)

1
2
3
4
5
6
1
2
3
4
5
6
7
8
9
4
6
7


JOIN

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))    # to join the array
print(c)
d=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
e=np.array_split(d,3)   #splitting an array into sub-arrays
print(e)

[1 2 3 4 5 6]
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


SORTING

In [ ]:
import numpy as np
random_array=np.array([129,63,-72,28,-321,0])  #sorting in ascending order
print(np.sort(random_array))

rand_bool=np.array([False,True, False, True]) #sorting booleans
print(np.sort(rand_bool))

i=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
odd=[]
even=[]
for a in i:
  if a%2 ==0:
    even.append(True)
  else:
      odd.append(False)


[-321  -72    0   28   63  129]
[False False  True  True]


In [ ]:
import numpy as np
i=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
odd=[]
even=[]
for a in i:
  if a%2 ==0:
    even.append(a)
  else:
    odd.append(a)
print("even no.s:", even)
print("odd no.s:", odd)

even no.s: [2, 4, 6, 8, 10, 12]
odd no.s: [1, 3, 5, 7, 9, 11]
